config/routes.rb
Rails.application.routes.draw do

  resources :articles do
    resources :comments
  end
  
  root 'welcome#index'
  
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments 
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index 
    @articles = Article.all
  end 
  
  def new 
    @article = Article.new 
  end 
  
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "Your article has been created"
      redirect_to articles_path 
    else 
      flash.now[:error] = "There is a problem with your form"
      render :new
    end 
  end 
  
  def show 
    @article = Article.find(params[:id])
  end 
  
  def edit 
    @article = Article.find(params[:id])
  end 
  
  def update 
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = "Updated successfully"
      redirect_to articles_path 
    else 
      flash[:error] = "Update failed"
      render :edit 
    end 
  end 
  
  def destroy 
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end 
  
  def delete 
    
  end 
  
  private 
  
  def article_params 
    params.require(:article).permit(:first_name, :last_name, :title, :text, :id)
  end 
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def index 
  end 
  
  def new
    @article = Article.find(params[:id])
    @commment = @article.comment.new 
  end 
  
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    if @comment.save
      flash[:success] = "Comment has been created"
      redirect_to article_path(@article)
    else 
      flash[:error] = "Comment failed"
      render :new
    end 
  end 
  
  def show
    article = Article.find(params[:article_id])
    @comment = article.comments.find(params[:id])
  end 
  
  def edit 
    article = Article.find(params[:article_id])
    @comment = article.comments.find(params[:id])
  end 
  
  def update
    article = Article.find(params[:article_id])
    @comment = article.comments.find(params[:id])
    if @comment.update(comment_params)
      flash[:success] = "Comment updated successfully"
      redirect_to article_comment_path(@comment.article, @comment)
    else 
      flash.now[:error] = "Comment Error"
      render :edit 
    end 
  end 
  
  def destroy
    article = Article.find(params[:article_id])
    @comment = article.comments.find(params[:id])
    @comment.destroy 
    redirect_to article_path(@comment.article)
  end 
  
  def delete 
  end 
  
  def comment_params
    params.require(:comment).permit(:name, :body, :id, :article_id)
  end 
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h2> Edit Form </h2>

<%= form_for @article do |f| %>

  <p> 
    <%= f.label :first_name %><br/>
    <%= f.text_field :first_name %>
  </p>
  
  <p>
    <%= f.label :last_name %></br/> 
    <%= f.text_field :last_name %>
  </p> 
  
  <p> 
    <%= f.label :title %></br/> 
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :text %></br/> 
    <%= f.text_area :text %>
  </p>
  
  <p> 
    <%= f.submit "Create new article" %>
  </p>
  
<% end %>

app/views/articles/index.html.erb
<h1> Welcome to the Index </h1>

<% @articles.each do |article| %>
  <table> 
    <tr>
      <th> Article #  </th>
      <th> First name </th>
      <th> Last  name </th>
      <th> Title      </th>
      <th> Text       </th>
      <th> Edit       </th>
      <th> Delete     </th>
    </tr>
    <tr> 
      <td> <%= article.id %>         </td>
      <td> <%= article.first_name %> </td>
      <td> <%= article.last_name  %> </td>
      <td> <%= article.title %>      </td>
      <td> <%= article.text %>       </td>
      <th> <%= link_to "Edit", edit_article_path(article) %>                   </th>
      <td> <%= link_to "Delete", article_path(article), method: :delete, data: 
      { confirm: "Are you sure?" } %> </td>
      
      <td> <%= link_to "Show", article_path(article) %> </td>
   </tr>
  </table>
  
<% end %>
  

app/views/articles/new.html.erb
<h2> New Form </h2>

<%= form_for @article do |f| %>

  <p> 
    <%= f.label :first_name %><br/>
    <%= f.text_field :first_name %>
  </p>
  
  <p>
    <%= f.label :last_name %></br/> 
    <%= f.text_field :last_name %>
  </p> 
  
  <p> 
    <%= f.label :title %></br/> 
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :text %></br/> 
    <%= f.text_area :text %>
  </p>
  
  <p> 
    <%= f.submit "Create new article" %>
  </p>
  
<% end %>

app/views/articles/show.html.erb
<h1> Show </h1>

<p> <%= @article.first_name%> </p>

<p> <%= @article.last_name %> </p>

<p> <%= @article.title %>     </p>

<p> <%= @article.text %>      </p>

<h2> Comments </h2>

<%  @article.comments.each do |comment| %> 
  <ul>                                            
    <Li> <%= comment.body %> | <%= link_to "Show", article_comment_path(comment.article, comment) %> | 
                               <%= link_to "Edit", edit_article_comment_path(comment.article, comment) %> 
                                <%= link_to "Delete", article_comment_path(comment.article, comment), method: :delete, 
                                data: { confirm: "Are you sure?" } %> 
                                </li> 
  </ul>
  
<% end %>


<h1> Add new comment </h1>

<%= form_for([@article, @article.comments.build]) do |f| %>

  <p> 
    <%= f.label :name %> <br/>
    <%= f.text_field :name %> 
  </p>
  
  <p>
    <%= f.label :body %> <br>
    <%= f.text_area :body %> 
  </p>
  
  <p>
    <%= f.submit "Create new comment" %>
  </p>


<% end %>


<b> <%= link_to "Edit", edit_article_path(@article) %> | <%= link_to "Back", articles_path %> </b>

app/views/comments/edit.html.erb
<h1> Edit Comment </h1>

<%= form_for [@comment.article, @comment] do |f| %>
  
  <p> 
    <%= f.label :name %> 
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>
  
  <p>
    <%= f.submit "Update" %>
  </p>

<% end %>

app/views/comments/new.html.erb
<h1> New comment </h1>

<%= form_for @article, @article.commments.build do |f| %>

  <p> 
    <%= f.label :name %> <br/>
    <%= f.text_field :name %> 
  </p>
  
  <p>
    <%= f.label :body %> <br>
    <%= f.text_area :body %> 
  </p>
  
  <p>
    <%= f.submit "Create new comment" %>
  </p>


<% end %>

app/views/comments/show.html.erb
<h1> Comment </h1>


<p> ID: <%= @comment.id %> </p> 

<p> NAME: <%= @comment.name %> </p> 

<p> BODY: <%= @comment.body %> </p> 

<%= link_to "Back", article_path(@comment.article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>